### DISCUSSION TITLE
Modifying CoreDNS and local-node-dns is overwritten when using Claudie

### DISCUSSION THREAD

**Discussion by smulikHakipod** [berops/claudie#1377] [General] [answered]
Hey and thanks for the great work!
I am modifing CoreDNS + local DNS in my Claudie cluster configmaps as explained in here https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/ . 
The problem I have is everytime I modify Claudie YAMLs, this config is being overwritten and reverted back to default, breaking my cluster as all the custom DNS records are deleted. 
Is there a way to workaround this behavior? 
Thanks!

**Comment by Despire** [comment]
Hi @smulikHakipod 

Can you give us some more feedback as to which changes you have made ? I wasn't able to reproduce this on my side.

I tried the following edit the configmap via

```
kubectl edit configmap -n kube-system coredns -o yaml --kubeconfig ./claudie-cluster
```

append 
```
    consul.local:53 {
        errors
        cache 30
        forward . 10.150.0.1
    }    
```
at the end of the Corefile for CoreDNS.

Then I tried to remove/add nodes in the Claudie YAML triggering the Claudie workflow and the changes in the config map persisted

**Comment by smulikHakipod** [comment]
Thanks @Despire 
I might be confusing here with something else. 
I tested again Coredns config - even with k8s version upgrade - coredns config is not being overwritten - this is probably my mistake and misunderstanding. 
Whats probably caused me this misunderstanding is that `node-local-dns` is being overwritten, causing DNS resloving to skip coredns config. 
I got this extra config in `node-local-dns` configmap
```
some-rds-crap.us-east-1.rds.amazonaws.com:53 {
  errors
  cache {
    success 9984 30
    denial 9984 5
  }
  reload
  loop
  bind __PILLAR__LOCAL__DNS__ __PILLAR__DNS__SERVER__
  forward . __PILLAR__CLUSTER__DNS__ {
          force_tcp
  }
  prometheus :9253
  health __PILLAR__LOCAL__DNS__:8080
  }
  ```

But even messing with autoscale max/min numbers e.g 

```
      - name: hetzner-worker  # add under nodePools.dynamic section
        providerSpec:
            name: hetzner-1   # use your new hetzner provider hetzner-1 to create these nodes
            region: fsn1
            zone: fsn1-dc14
        serverType: cpx51
        image: ubuntu-22.04
        autoscaler:          
            min: 1 # change to 0 or 1 caused config lost
            max: 4
```

I might not need to touch this stuff, but without changing this stuff, CoreDNS is completely bypassed. 

This might be just me trying to create workarounds that should not be happening? But then again - this local-node-dns mean there are multiple DNS configs, and CoreDNS on its own cannot really do much. 

Thanks
