### ISSUE TITLE
Bug: Static cluster still available after deletion

### ISSUE THREAD

**Issue by Despire** [berops/claudie#1029]
### Current Behaviour

If a cluster is created with static nodepools e.g.

```yaml
spec:
  nodePools:
    static:
    - name: static-pool-1
      nodes:
        - endpoint: 192.168.61.1
          secretRef:
            name: vm-1-secret
            namespace: secrets
    - name: static-pool-2
      nodes:
        - endpoint: 192.168.61.2
          secretRef:
            name: vm-2-secret
            namespace: secrets
  kubernetes:
    clusters:
      - name: cluster-test
        version: v1.26.0
        network: 192.168.2.0/24
        pools:
          control:
            - static-pool-1
          compute:
            - static-pool-2
```
After deletion of the InputManifests the kubeconfig from the cluster is still working meaning the nodes are still interconnected and operating as a kubernetes cluster

### Expected Behaviour

The above described case shouldn't happen after a Input Manifests is destroyed the cluster should no longer be accessible
### Steps To Reproduce
1. Build a Cluster from static nodepools.
2. Save the kubeconfig
3. Trigger a Deletion
4. Access cluster via the saved kubeconfig
