### ISSUE TITLE
Bug: Config with static nodepool rebuild multiple time, even if sucessful

### ISSUE THREAD

**Issue by Despire** [berops/claudie#1031]
### Current Behaviour

Applying the following config

```yaml
spec:
  nodePools:
    static:
    - name: static-pool-1
      nodes:
        - endpoint: 192.168.61.1
          secretRef:
            name: vm-1-secret
            namespace: secrets
    - name: static-pool-2
      nodes:
        - endpoint: 192.168.61.2
          secretRef:
            name: vm-2-secret
            namespace: secrets
  kubernetes:
    clusters:
      - name: cluster-test
        version: v1.26.0
        network: 192.168.2.0/24
        pools:
          control:
            - static-pool-1
          compute:
            - static-pool-2
```

i.e using static pools, results in the config being build several times (due to mistaching current state / desired state in the DB)

**Only occurs occasionally not every-time**
### Expected Behaviour

The config should only be build once and the current state and desired state must match after a successful build

### Steps To Reproduce
1. Apply the above config on static nodepools
2. Watch the Builder service and notice that after the config is sucessfully build the process then restarts again. (There is a mismatch in the DB for the current and desired state)
