### ISSUE TITLE
Chore: Lack of node labels for distinction.

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1033]
### Description

Nodes in a cluster build by Claudie do not contains any label with unique value. Most of the time the label with unique value is `kubernetes.io/hostname`, which Claudie currently doesn't support.
This might be an issue, when trying to apply Node Affinity, Pod Topology Spread Constraints or anything else, which requires clear uniqueness of the nodes.

In the following code space you can see all labels for each node in cluster, which was created by the InputManifest in **How to reproduce** section.

```
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    claudie.io/node-type=compute
                    claudie.io/nodepool=jkb-gcp-compute-ehve9n9
                    claudie.io/provider=gcp
                    claudie.io/provider-instance=gcp-1
                    kubernetes.io/arch=amd64
                    kubernetes.io/os=linux
                    topology.kubernetes.io/region=europe-west2
                    topology.kubernetes.io/zone=europe-west2-a
                    v1.kubeone.io/operating-system=ubuntu
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    claudie.io/node-type=compute
                    claudie.io/nodepool=jkb-gcp-compute-ehve9n9
                    claudie.io/provider=gcp
                    claudie.io/provider-instance=gcp-1
                    kubernetes.io/arch=amd64
                    kubernetes.io/os=linux
                    topology.kubernetes.io/region=europe-west2
                    topology.kubernetes.io/zone=europe-west2-a
                    v1.kubeone.io/operating-system=ubuntu
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    claudie.io/node-type=control
                    claudie.io/nodepool=jkb-gcp-control-exvmvv7
                    claudie.io/provider=gcp
                    claudie.io/provider-instance=gcp-1
                    kubernetes.io/arch=amd64
                    kubernetes.io/os=linux
                    topology.kubernetes.io/region=europe-west2
                    topology.kubernetes.io/zone=europe-west2-a
                    v1.kubeone.io/operating-system=ubuntu
```

### How to reproduce

Run `kubectl apply` with the following InputManifest in our `e2e` cluster.

``` yaml
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: jakub-test
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
    - name: jkb-gcp-control
      providerSpec:
        name: gcp-1
        region: europe-west2
        zone: europe-west2-a
      count: 1
      serverType: e2-small
      image: ubuntu-os-cloud/ubuntu-2204-jammy-v20221206
      storageDiskSize: 50
    - name: jkb-gcp-compute
      providerSpec:
        name: gcp-1
        region: europe-west2
        zone: europe-west2-a
      count: 2
      serverType: e2-small
      image: ubuntu-os-cloud/ubuntu-2204-jammy-v20221206
      storageDiskSize: 50
  kubernetes:
    clusters:
      - name: jakub-test
        version: v1.26.0
        network: 192.168.2.0/24
        pools:
          control:
            - jkb-gcp-control
          compute:
            - jkb-gcp-compute
```

### Exit criteria

- [ ] Add kubernetes.io/hostname or any other label, which can be used as a unique identifier for nodes
