### ISSUE TITLE
Bug: ghcr.io/berops/claudie/autoscaler-adapter image not found

### ISSUE THREAD

**Issue by gkowalsk** [berops/claudie#1100]
### Current Behaviour
When autoscaler-aws-cluster pod initializes the _ImagePullBackOff_ is displayed

### Expected Behaviour
The autoscaler-aws-cluster pod with status running

### Steps To Reproduce
1.  Loaded input manifest with autoscaling
```
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: awsmanifest
  labels:
    app.kubernetes.io/part-of: claudie
spec:

  providers:
    - name: aws-1
      providerType: aws
      secretRef:
        name: aws-secret-1
        namespace: claudie

  nodePools:
    dynamic:
      - name: control-aws
        providerSpec:
          name: aws-1
          region: eu-west-1
          zone: eu-west-1a
        count: 1
        serverType: t3.medium
        image: ami-0694d931cee176e7d
        storageDiskSize: 50

      - name: compute-1-aws
        providerSpec:
          name: aws-1
          region: eu-west-1
          zone: eu-west-1b
        count: 1
        serverType: t3.medium
        image: ami-0694d931cee176e7d
        storageDiskSize: 50
      - name: compute-2-aws
        providerSpec:
          name: aws-1
          region: eu-west-1
          zone: eu-west-1c
        autoscaler:
            min: 1
            max: 5
        serverType: t3.medium
        image: ami-0694d931cee176e7d
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: aws-cluster
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - control-aws
          compute:
            - compute-1-aws
            - compute-2-aws
```
2. claudie-operator reports status=DONE
3. autoscaler-aws-cluster pod pops up and produces an error below
```
3m43s (x3 over 4m20s)   Warning   Failed              Pod/autoscaler-aws-cluster-1lkxqbz-7d46cdd5c7-6hppl    Failed to pull image "ghcr.io/berops/claudie/autoscaler-adapter": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/berops/claudie/autoscaler-adapter:latest": failed to resolve reference "ghcr.io/berops/claudie/autoscaler-adapter:latest": ghcr.io/berops/claudie/autoscaler-adapter:latest: not found
```
