### ISSUE TITLE
Bug: scheduler stage error cluster with a static node defined

### ISSUE THREAD

**Issue by gkowalsk** [berops/claudie#1101]
### Current Behaviour
Scheduler reports an error when a local (on premise) static node is defined and used in a cluster.  
The error persists and is continuously reported by claudie-operator even the manifest is edited so that it no longer consists the offending parts.  
Manifest delete command locks.

### Expected Behaviour
All stages go through and build completes with status=DONE

### Steps To Reproduce
1. Load an input manifest for private cluster like
```
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  labels:
    app.kubernetes.io/part-of: claudie
  name: localmanifest
spec:
  kubernetes:
    clusters:
    - name: local-cluster
      network: 192.168.2.0/24
      pools:
        compute:
        - laptop-2
        control:
        - laptop-1
      version: v1.24.0
  nodePools:
    static:
    - name: laptop-1
      nodes:
      - endpoint: 192.168.122.51
        secretRef:
          name: static-node-key
          namespace: claudie
    - name: laptop-2
      nodes:
      - endpoint: 192.168.122.26
        secretRef:
          name: static-node-key
          namespace: claudie
```
3. scheduler log yields:
```
2023-11-10T08:53:45Z ERR Error while processing config error="error while saving the config: failed to save config via github.com/berops/claudie/proto/pb.ContextBoxServiceClient.SaveConfigScheduler-fm : rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
```

Manifest definition file was checked against UTF-8 compliance and linted.
