### ISSUE TITLE
Hetzner autoscaled nodepool without volume

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1110]
It seems like i can't launch a Hetzner autoscaled nodepool without a volume attached.
I've tried without `storageDiskSize` set and, as shown, with 0 as value, but both creates a volume for the node, with 50gb.
This is the code:
```
      - name: compute-hetzner-autoscaled
        providerSpec:
          name: hetzner
          region: hel1
          zone: hel1-dc2
        serverType: cax21
        storageDiskSize: 0
        image: ubuntu-22.04
        autoscaler:
          min: 1
          max: 10
```
