### ISSUE TITLE
Help: Loadbalancing

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1111]
I'm trying to figure out how to get loadbalancing to work with my apps.
I've set up my loadbalancer like this:
```
  loadBalancers:
    roles:
      - name: apiserver
        protocol: tcp
        port: 6443
        targetPort: 6443
        target: k8sControlPlane
      - name: https
        protocol: tcp
        port: 443
        targetPort: 443
        target: k8sComputePlane
      - name: http
        protocol: tcp
        port: 80
        targetPort: 80
        target: k8sComputePlane
    clusters:
      - name: apiserver-lb-dev
        roles:
          - apiserver
          - https
          - http
        dns:
          dnsZone: worldofpotter.eu
          provider: cloudflare
        targetedK8s: wox-cluster
        pools:
          - loadbalancer
```
And i've configured my app like this:
```
whoami:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
    - host: whoami.eye4web.dk
      paths:
      - /
    tls:
    - secretName: whoami-tls
      hosts:
      - whoami.eye4web.dk

```
I've pointed `whoami.eye4web.dk` to the LB ip address, but when going to the domain i get `ERR_EMPTY_RESPONSE`.
I've installed cert-manager in the cluster, and it looks like the certificate get issued correctly

If i describe the ingress it looks like this:
```
Name:             whoami
Labels:           app.kubernetes.io/instance=whoami
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=whoami
                  app.kubernetes.io/version=1.8.6
                  helm.sh/chart=whoami-2.7.0
Namespace:        whoami
Address:
Ingress Class:    nginx
Default backend:  <default>
TLS:
  whoami-tls terminates whoami.eye4web.dk
Rules:
  Host               Path  Backends
  ----               ----  --------
  whoami.eye4web.dk
                     /   whoami:80 (10.244.4.65:80)
Annotations:         cert-manager.io/cluster-issuer: letsencrypt
                     kubernetes.io/tls-acme: true
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  CreateCertificate  14m   cert-manager-ingress-shim  Successfully created Certificate "whoami-tls"
```

Can you point me in the right direction as to what i am missing?
