### ISSUE TITLE
Bug: Updating Hetzner autoscaler min is not processed

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1115]
I've created a cluster for the following nodepool:
```
      - name: compute-hetzner-autoscaled
        providerSpec:
          name: hetzner
          region: hel1
          zone: hel1-dc2
        serverType: cax21
        storageDiskSize: 0
        image: ubuntu-22.04
        autoscaler:
          min: 1
          max: 10
        labels:
          region: fi
```
When creating the cluster, it worked as expected, creating 1 node in the pool, but then i wanted to test increasing the `min` field, and it seems like nothing happens when i apply this new config, `min: 2`.
Status keeps as:
```
kubectl get inputmanifests.claudie.io xxx -o jsonpath='{.status}' | jq .
{
  "clusters": {
    "wox-cluster": {
      "phase": "NONE",
      "state": "DONE"
    }
  },
  "state": "DONE"
}
```
I also don't see anything about this in the logs of any of the Claudie pods.
