### ISSUE TITLE
Bug: Longhorn examples missing in example input manifest

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1125]
The docs have a section about storage solution and mentions Longhorn and to look in the example input manifest, but the example input manifest does not contain any mentions of longhorn.

**Comment by MiroslavRepka** [comment]
As per [docs](https://docs.claudie.io/v0.6.3/storage/storage-solution/#longhorn)

```
A Claudie-created cluster comes with the longhorn deployment preinstalled and ready to be used.
```

AFAIK, there is no API in input manifest to somehow customize it yet. Do you have any use case for user input in regards to longhorn? Or maybe docs improvement to make it more clear/visible? :)

**Comment by Danielss89** [comment]
A bit further down it states:
```
Besides the default storage class, Claudie can also create custom storage classes, which force persistent volumes to be created on specific nodes based on the provider instance they have. In other words, you can use a specific provider instance to provision nodes for your storage needs, while using another provider instance for computing tasks.
```
It was and example of above i would expect was linked to

**Comment by MiroslavRepka** [comment]
Oh, now I see your point. Lets build an example input manifest which would showcase this. Maybe if guys like it they can add it to the docs :)

So lets define 2 cloud provider instances. One will be used for storage, and one will be used for compute resources.

```yaml
   - name: storage-provider
      providerType: hetzner
      secretRef:
        name: storage-provider-secrets
        namespace: claudie-secrets
   - name: compute-provider
      providerType: hetzner
      secretRef:
        name: compute-provider-secrets
        namespace: claudie-secrets
```

Now that we have this, we can define a few nodepools. Lets say, one nodepool will be used for storage, while other will be used for workflows

```yaml
      - name: datastore-nodepool
        providerSpec:
          name: storage-provider
          region: hel1
          zone: hel1-dc2
        count: 5
        serverType: cpx21
        image: ubuntu-22.04
        storageDiskSize: 800
        taints:
          - key: node-type
            value: datastore
            effect: NoSchedulee
 
      - name: compute-nodepool
        providerSpec:
          name: compute-provider
          region: hel1
          zone: hel1-dc2
        count: 10
        serverType: cpx41
        image: ubuntu-22.04
        taints:
          - key: node-type
            value: compute
            effect: NoSchedulee
```

This should result in 2 distinct storage classes being created; `longhorn-storage-provider-zone` and `longhorn-compute-provider-zone`.

Now all you have to do is specify correct storage class when defining your PVCs. 

Full example manifest (together with control nodepool and LB):
```yaml
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: ExampleManifestForStorageClasses
  labels:
    app.kubernetes.io/part-of: claudie
spec:

  providers:
    - name: storage-provider
      providerType: hetzner
      secretRef:
        name: storage-provider-secrets
        namespace: claudie-secrets

    - name: compute-provider
      providerType: hetzner
      secretRef:
        name: storage-provider-secrets
        namespace: claudie-secrets

    - name: dns-provider
      providerType: cloudflare
      secretRef:
        name: dns-provider-secret
        namespace: claudie-secrets

  nodePools:
    dynamic:
        - name: control-nodepool
          providerSpec:
            name: compute-provider
            region: hel1
            zone: hel1-dc2
          count: 3
          serverType: cpx21
          image: ubuntu-22.04

        - name: datastore-nodepool
          providerSpec:
            name: storage-provider
            region: hel1
            zone: hel1-dc2
          count: 5
          serverType: cpx21
          image: ubuntu-22.04
          storageDiskSize: 800
          taints:
            - key: node-type
              value: datastore
              effect: NoSchedule
  
        - name: compute-nodepool
          providerSpec:
            name: compute-provider
            region: hel1
            zone: hel1-dc2
          count: 10
          serverType: cpx41
          image: ubuntu-22.04
          taints:
            - key: node-type
              value: compute
              effect: NoSchedule

        - name: loadbalancer-nodepool
          providerSpec:
            name: compute-provider
            region: hel1
            zone: hel1-dc2
          count: 1
          serverType: cpx21
          image: ubuntu-22.04

  kubernetes:
    clusters:
      - name: my-awesome-claudie-cluster
        version: v1.26.0
        network: 192.168.2.0/24
        pools:
          control:
            - control-nodepool
          compute:
            - datastore-nodepool
            - compute-nodepool

  loadBalancers:
    roles:
      - name: apiserver
        protocol: tcp
        port: 6443
        targetPort: 6443
        target: k8sControlPlane

    clusters:
      - name: apiserver-lb
        roles:
          - apiserver
        dns:
          dnsZone: dns-zone
          provider: dns-provider
        targetedK8s: my-awesome-claudie-cluster
        pools:
          - loadbalancer-nodepool

```

Hope this helps!
