### ISSUE TITLE
Bug: Longhorn CSI pods not deployed on nodes with taints

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1186]
It seems that the longhorn pods `longhorn-csi-plugin` and `csi-attacher` cannot be scheduled on nodes with taints.
I can see `engine-image-ei`, `instance-manager`, `instance-manager`.

I found this as i was deploying pods with pvcs on these instances and i get the error:
```
AttachVolume.Attach failed for volume "pvc-a65c0de4-aeea-49e6-97c0-a6e1be4f1ea1" : CSINode hong-1 does not contain driver driver.longhorn.io
```

**Comment by Danielss89** [comment]
I have servers in different countries, and for servers in China, Japan, Indonesia, i want to repel all pods for those servers, except for those that fits in that countries, so as i've understodd that is the way to go. So for that i'm using both taints and labels.
Example: 
```
        labels:
          region: hong
        taints:
          - key: "region"
            value: "hong"
            effect: "NoSchedule"
```
I would still expect system pods to be able to be deployed there, for example network CNI(which does) and something like Longhorn i would also expect to be working on ALL my servers, no matter the taints, so that i can deploy pods which needs pvc's.
