### ISSUE TITLE
Bug: OCI apt keys

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#1237]
While testing out new feature, I ecountered repetetive errors in kube-eleven when using OCI nodes:
Trimmed error from kube-eleven:

**The repository XX is no longer signed.**
```
 Failed to fetch http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  403  Forbidden [IP: 34.107.204.206 80]\nE: The repository 'http://apt.kubernetes.io kubernetes-xenial InRelease' is no longer signed.\n" node=130.61.17.72
```

**Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg)**
```
https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\nW: http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\n+ sudo DEBIAN_FRONTEND=noninteractive apt-get install --option Dpkg::Options::=--force-confold -y --no-install-recommends apt-transport-https ca-certificates curl gnupg lsb-release rsync\n+ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg\n+ sudo apt-key add -\nWarning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).\n+ echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main'\n+ sudo tee /etc/apt/sources.list.d/kubernetes.list\n+ sudo apt-get update\nW: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\nW: http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\n+ kube_ver='1.24.0*'\n+ cni_ver='1.1.1*'\n+ sudo apt-get update\n]
```

The OCI definition in inputManifest (from test-set1)
```
      - name: oci-control
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-1
        count: 3
        serverType: VM.Standard2.1
        # ubuntu minimal
        # https://docs.oracle.com/en-us/iaas/images/image/674d0b41-aee8-4c0b-bf99-9e100d90f241/
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaavvsjwcjstxt4sb25na65yx6i34bzdy5oess3pkgwyfa4hxmzpqeq
        taints:
          - key: test
            effect: NoSchedule
```
