### ISSUE TITLE
Bug: hetzner cloud deployment issue

### ISSUE THREAD

**Issue by ninokotur** [berops/claudie#1268]
### Current Behaviour
any form of kubernetes deployment on hetzner cloud fails with following
 module=kube-eleven
2024-03-06T11:53:17Z WRN Error encountered while executing kubeone apply -m kubeone.yaml -y --log-format json : exit status 10 module=kube-eleven
2024-03-06T11:53:17Z INF Next retry in 10s... module=kube-eleven
2024-03-06T11:53:27Z WRN Retrying command kubeone apply -m kubeone.yaml -y --log-format json... (1/2) module=kube-eleven

### yaml used to deploy
```
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: kubernetes-hetzner
spec:
  providers:
      - name: hetzner-secret
        providerType: hetzner
        secretRef:
          name: hetzner-secret
          namespace: default
  nodePools:
    dynamic:
      - name: control-hetzner-1
        providerSpec:
          name: hetzner-secret
          region: fsn1
          zone: fsn1-dc14
        count: 1
        serverType: cpx21
        image: ubuntu-22.04

      - name: compute-hetzner-1
        providerSpec:
          name: hetzner-secret
          region: fsn1
          zone: fsn1-dc14
        count: 1
        serverType: cpx21
        image: ubuntu-22.04
        storageDiskSize: 50
  kubernetes:
    clusters:
      - name: hetzner-cluster
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - control-hetzner-1
          compute:
            - compute-hetzner-1
```

I have tried different number of computes different number of control nodes, different operating systems, different kuberentes versions but all have same ending cluster doesn't inicialize, every fails inside kube-eleven deployment. VMs on hetzner cloud are created properly alongside with default firewall rules.
