### ISSUE TITLE
Bug: Claudie doesn't support multiple Provider configurations for the same cloud provider

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1296]
### Current Behaviour

Using multiple [Provider](https://docs.claudie.io/latest/input-manifest/api-reference/#providers) (at least two) configurations for the same cloud provider results in the following error in `terraformer`

```
Error: Duplicate provider configuration
jakub-blog-test-z7ep12d │ 
jakub-blog-test-z7ep12d │   on jakub-blog-test-z7ep12d-azure-2-provider.tf line 1:
jakub-blog-test-z7ep12d │    1: provider "azurerm" {
jakub-blog-test-z7ep12d │ 
jakub-blog-test-z7ep12d │ A provider configuration for "azurerm" with alias "nodepool" was already
jakub-blog-test-z7ep12d │ given at jakub-blog-test-z7ep12d-azure-1-provider.tf:1,1-19. Each
jakub-blog-test-z7ep12d │ configuration for the same provider must have a distinct alias.
```

### Expected Behaviour

Claudie builds an infrastructure for the same cloud provider using multiple Provider configurations.

### Steps To Reproduce
1. Create at least two secrets for [Providers](https://docs.claudie.io/latest/input-manifest/api-reference/#providers) configuration. I created one secret with credentials for our sponsorship subscription and the other one with our pay-as-you-go subscription credentials.
2. Apply an InputManifest that provisions at least two node pools, each with a different Provider configuration. I've used the following one
```yaml
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: jakub-blog-test
  labels:
    app.kubernetes.io/part-of: claudie
spec:
  providers:
    - name: cloudflare-1
      providerType: cloudflare
      secretRef:
        name: cloudflare-secret
        namespace: default
    - name: azure-1
      providerType: azure
      secretRef:
        name: berops-azure-secret
        namespace: default
    - name: azure-2
      providerType: azure
      secretRef:
        name: sponsor-azure-secret
        namespace: default

  nodePools:
    dynamic:
      - name: control-azure-1
        providerSpec:
          name: azure-1
          region: westeurope
          zone: "1"
        count: 1
        serverType: Standard_B2s
        image: Canonical:0001-com-ubuntu-minimal-jammy:minimal-22_04-lts:22.04.202212120

      - name: compute-azure-1
        providerSpec:
          name: azure-1
          region: westeurope
          zone: "2"
        count: 1
        serverType: Standard_B2s
        image: Canonical:0001-com-ubuntu-minimal-jammy:minimal-22_04-lts:22.04.202212120
        storageDiskSize: 50

      - name: compute-azure-2
        providerSpec:
          name: azure-1
          region: northeurope
          zone: "3"
        count: 1
        serverType: Standard_B2s
        image: Canonical:0001-com-ubuntu-minimal-jammy:minimal-22_04-lts:22.04.202212120
        storageDiskSize: 50

      - name: loadbalancer-1
        providerSpec:
          name: azure-1
          region: northeurope
          zone: "1"
        count: 1
        serverType: Standard_B2s
        image: Canonical:0001-com-ubuntu-minimal-jammy:minimal-22_04-lts:22.04.202212120
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: jakub-blog-test
        version: "v1.26.0"
        network: 192.168.2.0/24
        pools:
          control:
            - control-azure-1
          compute:
            - compute-azure-1
            - compute-azure-2
  loadBalancers:
    roles:
      - name: apiserver
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - control-azure-1
    clusters:
      - name: apiserver-lb-claudie
        roles:
          - apiserver
        dns:
          dnsZone: claudie.dev
          provider: cloudflare-1
        targetedK8s: jakub-blog-test
        pools:
          - loadbalancer-1
```
It should also work without a loadbalancer.

### Anything else to note
This issue first occurred in this [blog](https://blog.alterway.fr/claudie-un-manager-de-clusters-kubernetes-multi-cloudhybrides.html).
