### ISSUE TITLE
Bug: Claudie doesn't allow nodes from two different AWS provider instances in the same region

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#1312]
### Current Behaviour
Currently, Claudie doesn't allow the following configuration:

```
spec:
  providers:
    - name: aws-team1
      providerType: aws
...
    - name: aws-team2
      providerType: aws
...
  nodePools:
    dynamic:
      - name: control-aws
        providerSpec:
          name: aws-team1
          region: eu-west-1
      - name: compute-aws
        providerSpec:
          name: aws-team2
          region: eu-west-1
```

### Expected Behaviour
Sometimes, the users might want to deploy nodepools in the same region, by two different providers (e.g. for billing, reporting or security issues).

### Anything else to note
Currently, I see the options to set `provider.alias` to e.g.:
- `nodepool_{{ $provider.name }}_{{ $provider.region }}`
- `nodepool_{{ substr(sha256($provider.name + $provider.region), 0, 4) }}`
- `nodepool_{{ $random }}`

### References
- https://github.com/berops/claudie/issues/1296
- https://github.com/berops/claudie/blob/master/services/terraformer/templates/aws/provider.tpl
