### ISSUE TITLE
Bug: Bug with new 0.8.0 'DynamicNodePool.Name' Error:Field validation for 'Name' failed on the 'max' tag

### ISSUE THREAD

**Issue by yaronshanisima** [berops/claudie#1380]
with this config 
```
apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: sima-k8s-04
  namespace: default
  labels:
    app.kubernetes.io/part-of: claudie
spec:
  providers:
    - name: hetzner-1
      providerType: hetzner
      secretRef:
        name: hetzner-secret-cloud
        namespace: default

  nodePools:
    dynamic:
      - name: control-hetzner
        providerSpec:
          # Name of the provider instance.
          name: hetzner-1
          # Region of the nodepool.
          region: fsn1
          # Datacenter of the nodepool.
          zone: fsn1-dc14
        count: 1
        # Machine type name.
        serverType: cpx11
        # OS image name.
        image: ubuntu-22.04
    static:
      - name: hertzner-1
        nodes:
          - endpoint: "10.0.1.2"
            secretRef:
              name: hertzner-key-01
              namespace: default

        labels:
          datacenter: hertzner-1
        annotations:
          node.longhorn.io/default-node-tags: '["hertzner-1"]' 

 clusters.
  kubernetes:
    clusters:
      - name: dev-cluster
        version: v1.27.3
        network: 192.168.2.0/24
        pools:
          control:
            - control-hetzner
          compute:
            - hertzner-1
            
   ```
   
   I am getting 
   ```
Error from server (Forbidden): error when creating "c.yaml": admission webhook "validate-manifest.claudie.io" denied the request: failed to validate nodepools section inside manifest: failed to validate DynamicNodePool "control-hetzner": Key: 'DynamicNodePool.Name' Error:Field validation for 'Name' failed on the 'max' tag
```

Did not happen with the previous Claudie version. 

Thanks!
