### ISSUE TITLE
Bug: Can't Update manifest after wrong nodepool definition

### ISSUE THREAD

**Issue by Despire** [berops/claudie#1483]
### Current Behaviour

If I provide a wrong nodepool definition
```
      - name: htz1
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx113
        image: ubuntu-22.04
        storageDiskSize: 50
```
Note the `serverType` cpx113 (which doesn't exists) when I try to delete this nodepool and replace it with a correct one (since nodepools are immutable) the current state stored in the db will still hold this wrong value and the updated input manifest with the new nodepool will fail.
### Expected Behaviour

The Update should handle the above described case.

### Steps To Reproduce

1. create wrong nodepool
```
      - name: htz1
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx113
        image: ubuntu-22.04
        storageDiskSize: 50

```
2. Replace with correct nodepool
```
      - name: htz2
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-22.04
        storageDiskSize: 50

```
3. See the update will fail
