### ISSUE TITLE
Bug: Image tags are generated by CI are invalid

### ISSUE THREAD

**Issue by jaskeerat789** [berops/claudie#153]
### Current Behavior:
When CI is builds the images, it adds a tag to them which is invalid and cannot we used in k8s cluster. The building and pushing of image is successful though.
As you can see in the code block below, the `kubectl get pods` throws an error for images that were build in the CI run.
```
NAME                            READY   STATUS             RESTARTS   AGE
builder-77ff894599-zlmbc        1/1     Running            0          13m
context-box-d5cf55c7b-5f64b     1/1     Running            2          13m
frontend-596f7d4576-m8dd6       2/2     Running            0          13m
kube-eleven-f89554d88-jpc6l     0/1     InvalidImageName   0          13m
mongodb-6477b97f9b-dj2kt        1/1     Running            0          13m
scheduler-7c99495568-txpcc      1/1     Running            0          13m
terraformer-755447f6b8-77hgm    1/1     Running            0          13m
wireguardian-84d7c7c658-rr6kq   0/1     InvalidImageName   0          13m
```

After going through the `kustomization.yaml` we can notice the image tag is starting with `-` and k8s is not happy about it.
``` 
images:
- name: eu.gcr.io/platform-infrastructure-316112/platform/builder
  newTag: 3c60d0a26c013e2575b122364300a774883400b3
- name: eu.gcr.io/platform-infrastructure-316112/platform/context-box
  newTag: 3c60d0a26c013e2575b122364300a774883400b3
- name: eu.gcr.io/platform-infrastructure-316112/platform/kube-eleven
  newTag: "-438"
- name: eu.gcr.io/platform-infrastructure-316112/platform/scheduler
  newTag: 3c60d0a26c013e2575b122364300a774883400b3
- name: eu.gcr.io/platform-infrastructure-316112/platform/terraformer
  newTag: 3c60d0a26c013e2575b122364300a774883400b3
- name: eu.gcr.io/platform-infrastructure-316112/platform/testing-framework
  newTag: "-438"
- name: eu.gcr.io/platform-infrastructure-316112/platform/wireguardian
  newTag: "-438"
  ```
  
### Expected Behavior:
The image tag should not start with a `-`.
