### ISSUE TITLE
Bug: Changing kubernetes version does not trigger build process

### ISSUE THREAD

**Issue by Despire** [berops/claudie#1604]
### Current Behaviour

Changing the kubernetes version to a higher version does not trigger the build process, but moves the manifest to `Done` state nevertheless.

```yaml
  kubernetes:
    clusters:
      - name: test
        version: 1.29.0 -> 1.30.0
```

### Expected Behaviour

Changing just the kubernetes version should trigger the build process
