### ISSUE TITLE
Feature: Support domain name routing using the same Load balancer node pool

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#1662]
### Motivation

I want to load balance the traffic in my K8s based on the subdomain. This means `postgres.example.com` should forward the traffic to the running Postgres application and `grafana.example.com` should forward the traffic to the running Grafana application.

### Description

ATM I have to create two different load balancer node pools to achieve the use case described in the Motivation. This brings an additional cost that can be cut if Claudie supports using multiple subdomains using the same Load balancer node pool.

### Exit criteria
- [ ]  Claudie supports subdomain routing for the applications using the same Load balancer node pool.

**Comment by Despire** [comment]
I would propose to add an `alternativeNames` field in the DNS that would in addition to the current `hostname` create additional A records that would point to the load balancers.


```
  loadBalancers:
    roles:
      - name: kubeapi-server
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - control-nodes
     - name: postgres
        protocol: tcp
        port: 5432
        targetPort: 30432
        targetPools:
          - compute-nodes
    - name: grafana
        protocol: tcp
        port: 8080
        targetPort: 30808
        targetPools:
          - compute-nodes
    - name: app1
        protocol: tcp
        port: 8081
        targetPort: 30809
        targetPools:
          - compute-nodes
    - name: app2
        protocol: tcp
        port: 8082
        targetPort: 30810
        targetPools:
          - compute-nodes
    clusters:
      - name: example-lb
        roles:
          - kubeapi-server
          - postgres
          - grafana
          - app1
          - app2
        dns:
          dnsZone: example.com
          provider: cloudflare-1
          hostname: postgres
          alternativeNames:
            - grafana
            - app1
            - app2
        targetedK8s: example-k8s
        pools:
          - lb
```

This would end-up creating 4 A records (postgres.example.com, grafana.example.com, app1.example.com, app2.example.com) that would all target the same loadbalancers nodes and the loadbalancers would then distribute the traffic based on the assigned roles.

@bernardhalas, @JKBGIT1
