### ISSUE TITLE
Feature: Avoid using `latest` templates by default and consider pinning via CRD

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#1758]
### Motivation
`terraformer` template selection currently defaults to the `latest` git tag. This is not a good behavior, because sometimes new template changes might have a Claudie upgrade as a dependency and the switch to a new template needs to happen in a controlled manner.

Moreover, should the user override templates for several providers, this issue proposes a new CRD object, that will avoid copy/pasting code over the `InputManifest.spec.providers` blocks and will also allow improving UX for migrating all the cluster manifests to a new version; in such a case only one modification is required - in the Custom Resource.

### Description
By default, this issue proposes that Claudie always takes templates from git tag identical with the Claudie release (e.g. `v0.9.10`). The repo/tag selection could be overridden via the following API: https://docs.claudie.io/latest/input-manifest/external-templates/; or alternatively via the below CRD, should the below proposal be accepted.

Now, as a part of this topic, we propose moving the template reference to a custom CRD:
```yaml
apiVersion: claudie.io/v1beta1
kind: TemplateReference
metadata:
  name: private-templates
  labels:
    app.kubernetes.io/part-of: claudie
spec:
  repository: "https://git.somehost.io/claudie-templates"
  tag: "v0.9.10"
  path: "production"
```
The `path` further expects `production/terraformer/<provider (e.g. genesiscloud)>`

On top of this, we suggest to always deploy the following custom resource within the install guide:
```yaml
apiVersion: claudie.io/v1beta1
kind: TemplateReference
metadata:
  name: upstream-templates
  labels:
    app.kubernetes.io/part-of: claudie
spec:
  repository: "https://github.com/berops/claudie-config"
  tag: "v0.9.10"
  path: "templates"
```

Such a `TemplateReference` will be referenced in the `InputManifest` the following way:
```yaml
spec:
  providers:
    - name: genesiscloud
      providerType: genesiscloud
      templateRef: private-templates # optional, default to `upstream-templates`
      secretRef:
        name: genesiscloud-secret
        namespace: secrets
```

The CRD, should it exist, will take a precedence over the `template:` stanza.

### Exit criteria

- [ ] Optionally, migrate the template version pinning API to a CRD
- [ ] By default, always consume the templates from the tag, that matches Claudie release tag

**Comment by Despire** [comment]
The `TemplateRepository` CRD could be useful if you would have many InputManifests referencing the same templates, which would skip some boilerplate and possible typos copy/paste errors, I could see a reason for the  CRD for defining the Templates and referencing it, instead of defining it in the InputManifest directly. Thats the only pro I can think of compared to the current solution


Additionally, for future use cases where anyone could define their own version of say ansible-playbooks/manifests to be deployed we would also need to implement another CRD that would be referenced per-cluster, for this I would like to use the `Settings` CRD introduced in the Envoy PR.

It allows you to reference a `Setting` custom resource at Role level of the loadbalancer that overwites the default configs that claudie ships with custom ones.

```diff
...
  loadBalancers:
    roles:
      - name: apiserver
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
            - control-pools
        settings:
            proxyProtocol: true
            stickySessions: false
+        settingsRef:
+          name: custom-envoy
+          namespace: claudie
...

This could be then further extented to be also used at the kuberentes cluster level for custom ansible-playbooks/manifests

```diff
  kubernetes:
    clusters:
      - name: dev-cluster
        version: 1.27.0
        network: 192.168.2.0/24
+     settingsRef:
+        name: custom-manifests
+        namespace: claudie
        pools:
          control:
            - control-htz
            - control-gcp
          compute:
            - compute-htz
            - compute-gcp
            - compute-azure
            - htz-autoscaled
is the default value.

```

and the `Settings` CRD would look like 

```
apiVersion: claudie.io/v1beta1
kind: Setting
metadata:
  name: custom-envoy
  namespace: claudie
  labels:
    app.kubernetes.io/part-of: claudie
spec:
  envoy:
    lds: |
         ...
    cds: |
         ...
```

```
apiVersion: claudie.io/v1beta1
kind: Setting
metadata:
  name: custom-manifests
  namespace: claudie
  labels:
    app.kubernetes.io/part-of: claudie
spec:
  ansible:
    playbooks: ["list of items to download and apply"]
```

There could be multiple `Settings` created or simply a single giant one that would be referenced at different levels in the `InputManifest` and always the context relavant to where it was referenced would be extracted.

So if you would reference the `custom-envoy` at the kubernetes cluster level it would do nothing as it would extract `spec.ansible` or `spec.manifests` overwrites which would be empty.
