### ISSUE TITLE
Feature: Change `dns.Project` to `dns.Provider`

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#201]
### Motivation:

Currently, in the input manifest, under the `loadbalancers.clusters.[].dns` we specify the `project` field. This was okay, however in #188, we added `project` field under the provider. Now, we have two different fields, which hold the same value. It would be neater if we replaced `dns.project` with `dns.provider` in the input manifest. Whatsmore, in the [go code](https://github.com/Berops/platform/blob/b0f61f79744a968fa68d733332e4a46bc9c53260/proto/config.proto#L70), we already have a provider under the `DNS`.

### Description:

Change the input manifest spec for `loadbalancers.clusters.[].dns` to have a `provider` field instead of `project`.
Current
```yaml
providers:
  - name: gcp-1
    credentials: super-secret-credentials
    gcp_project: project-id
...

loadBalancers:
  roles:
    ...
  clusters:
    - name: c-1
      dns: 
        dns_zone: claudie-zone
        project: project-id
      ...
```
New
```yaml
providers:
  - name: gcp-1
    credentials: super-secret-credentials
    gcp_project: project-id
...

loadBalancers:
  roles:
    ...
  clusters:
    - name: c-1
      dns: 
        dns_zone: claudie-zone
        provider: gcp-1
      ...
```

### Exit criteria:
- [x] Change for the input manifest was documented in `docs`
- [x] Appropriate changes were added into the go code
