### ISSUE TITLE
Feature: Rework the provider spec in input manifest

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#208]
### Motivation:

Currently, in the input manifest, provider specification is all over the place. We first define them in the `providers` list, and then we reference their name under the `nodepools.dynamic` list, which is very unintuitive. And lastly, we don't even specify it for DNS, we only use `project` field. I propose to rework the providers as follows:

Current
```yaml
providers:
  - name: hetzner
    credentials: abcd1234
  - name: gcp
    credentials: sak.json
    gcp_project: project-id  # why should every provider have gcp_project field, even if empty

nodePools:
  dynamic:
    - name: hetzner-control
      provider:
        hetzner:         # this does not make much sense
          region: nbg1
          zone: nbg1-dc3
      count: 3
      server_type: cpx11
      image: ubuntu-20.04
      disk_size: 50

kubernetes:
  ...

loadBalancers:
  roles: 
     ...
  clusters:
    - name: ts2-lb-2
      roles:
        - apiserver-lb
      dns: 
        dns_zone: lb-zone-2
        project: platform-296509   # why is the project here and not provider
      targeted-k8s: ts2-c-2
      pools:
        - gcp-lb
        - hetzner-lb
```
New
```yaml
providers:
  hetzner: 
      - name: hetzner-1
        credentials: abcd1234
      - name: hetzner-2
        credentials: efgh5678
  gcp:
      - name: gcp-1
        credenials: sak1.json
        project: project-1
      - name: gcp-2
        credenials: sak2.json
        project: project-2
  azure:
      - name: ....
      # other azure specific fields

nodePools:
  dynamic:
    - name: compute-gcp
      providerSpec:
        name: gcp-1
        region: europe-west1
        zone: europe-west1-c
      count: 2
      server_type: e2-small
      image: ubuntu-os-cloud/ubuntu-2004-focal-v20220610
      disk_size: 50

kubernetes:
  ...

loadBalancers:
  roles:
    ...
  clusters:
    - name: ts2-lb-1
      roles:
        - apiserver-lb
      targeted-k8s: k8s-cluster
      pools:
        - gcp-lb
        - hetzner-lb
      dns:
        dns_zone: lb-zone-2
        provider: gcp-1
```
### Description:

The providers in input manifest have been reworked to make it more clean and logical

### Exit criteria:
- [ ] New provider schemas have been design
- [ ] The designed schemas have been implemented
- [ ] Docs have been updated

Note:
I am open to any other suggestion :slightly_smiling_face:
