### ISSUE TITLE
Bug: k8s-sidecar in frontend will overwrite the file it creates if the field name is the same

### ISSUE THREAD

**Issue by MiroslavRepka** [Berops/claudie#225]
### Current Behavior:

The k8s-sidecar is used to pull the secrets out of the cluster containing the input manifest and save them to the frontends file system. However, the k8s-sidecar is creating files based on the field name inside the secret, not the secret name. Therefore, if the client would create two secrets, e.g.
secret1.yaml
```yaml
apiVersion: v1
metadata:
  name: manifest-1
  labels:
    claudie.io/input-manifest: manifest-1
type: Opaque
data:
  secretdata: "claudie manifest 1"
```
secret2.yaml
```yaml
apiVersion: v1
metadata:
  name: manifest-2
  labels:
    claudie.io/input-manifest: manifest-2
type: Opaque
data:
  secretdata: "claudie manifest 1"
```
the k8s-sidecar would create only a single file called `secretdata`.

### Expected Behavior:

K8s-sidecar should not overwrite the input manifest if they have the same field name in secret, rather create separate files for different secrets.

### Steps To Reproduce:

1. Run the claudie inside the cluster
2. Deploy 2 secrets with the same field name
3. Exec inside the frontend pod
4. See only a single file saved in `/input-manifests` directory
