### ISSUE TITLE
Bug: InstallVPN fails on unreachable node

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#276]
### Current Behavior:

Every once in a while we see an error in pipelines stating 
```
Error in test-set1 : error while calling InstallVPN on Ansibler: rpc error: code = Unknown desc = error encountered while installing VPN : exit status 2
```
When I started investigating, I found out that the playbook is failing due to one of the nodes being unreachable. After checking the Ansibler pod is not able to connect to the node (tried ping, telnet on port 22). @MarioUhrik and I then looked further and we did a few experiments:
- ping/telnet the node from local machine -> works
- ping/telnet the node from Ansibler pod -> doesn't work
- ping/telnet the node from a different pod in the same namespace -> doesn't work
- ping/telnet the node from `default` namespace -> doesn't work
- ping/telnet the node from dev cluster worker node -> doesn't work
- ping/telnet the worker node in the dev cluster from the "unreachable" node - works

As you can see, the connection from the dev cluster is being blocked somewhere, but we have no idea where and why. We also checked `iptables` but there was nothing suspicious there. The firewall rules on both ends looked fine as well.

The only leads we have is that we recently changed the base Ansibler image, so maybe there is something going on there. Also we suspect it might be something with the IP range of the node, since its always a hetzner node and always just one.

The IP we were testing on was `195.201.24.120` - please update the issue with more IPs if you encounter the bug.
GCP node unreachable - IP `35.246.47.28`

### Expected Behavior:

The Ansibler should be able to connect to all of the nodes Terraformer created.

### Steps To Reproduce:
Example: steps to reproduce the behavior:
1. Run test-set in cluster
2. Wait until the error occurs (around 4/10 times the pipeline runs)

### Anything else to note:

This bug was seen always in test-set1

**Comment by cloudziu** [comment]
After a consultation with @MiroslavRepka we think I came across this one with slightly different scenario.

So I've deployed a k8s cluster with RKE on Hetzner as a host for Claudie deployment. Installed Claudie on it and started provisioning cluster. The input manifest:
```
name: Scenario-1
providers:
nodePools:
  dynamic:
    - name: m-hetzner
      providerSpec:
        name: hetzner-1
        region: fsn1
        zone: fsn1-dc14
      count: 1
      server_type: cx41
      image: ubuntu-20.04
      disk_size: 100 

    - name: w-hetzner
      providerSpec:
        name: hetzner-1
        region: fsn1
        zone: fsn1-dc14
      count: 2
      server_type: cx41
      image: ubuntu-20.04
      disk_size: 100

    - name: m-gcp
      providerSpec:
        name: gcp-1
        region: europe-west3
        zone: europe-west3-a
      count: 1
      server_type: e2-standard-4
      image: ubuntu-os-cloud/ubuntu-2004-focal-v20220610
      disk_size: 50
    - name: w-gcp
      providerSpec:
        name: gcp-1
        region: europe-west3
        zone: europe-west3-a
      count: 1
      server_type: e2-standard-4
      image: ubuntu-os-cloud/ubuntu-2004-focal-v20220610
      disk_size: 100

    - name: m-oci
      providerSpec:
        name: oci-1
        region: eu-frankfurt-1
        zone: hsVQ:EU-FRANKFURT-1-AD-3
      count: 1
      server_type: VM.Standard2.1
      # ubuntu minimal
      # https://docs.oracle.com/en-us/iaas/images/image/7c71896e-e030-4de2-b73e-8856ac44d84c/
      image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaauj7omj2zxmbh2go5plujbvysvhwojasdywcxrnnkcwehvwpix3ga
      disk_size: 50
    - name: w-oci
      providerSpec:
        name: oci-1
        region: eu-frankfurt-1
        zone: hsVQ:EU-FRANKFURT-1-AD-3
      count: 2
      server_type: VM.Standard2.1
      # ubuntu minimal
      # https://docs.oracle.com/en-us/iaas/images/image/7c71896e-e030-4de2-b73e-8856ac44d84c/
      image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaauj7omj2zxmbh2go5plujbvysvhwojasdywcxrnnkcwehvwpix3ga
      disk_size: 100

kubernetes:
  clusters:

    - name: scenario-1
      version: v1.23.0
      network: 192.168.2.0/24
      pools:
        control:
          - m-hetzner
          - m-gcp
          - m-oci
        compute:
          - w-hetzner
          - w-gcp
          - w-oci
```

First issue what I've encountered was extended time of installing wireguard (with a success at the end).  I've described it [here](https://github.com/Berops/claudie/issues/524).   

After the `ansibler` finished his job, `kube-eleven` is unable to connect to Claudie deployed GCP Nodes. It cannot discover the nodes via ssh. After some of troubleshooting it came out that the one of the Hetzner nodes on witch `tube-eleven` was running could not connect to GCP resources. 
I was able to ssh:
My local PC
Other Hetzner Nodes (Node1 and Node2)
Pods located on the N1 and N2

I wasn't able to ssh:
kube-eleven (located on Node3)
Node3 itself

The Node3 was able to ssh to Claudie created OCI and Hetzner instances without any problem.

Following @MiroslavRepka suggestion, I wanted to describe my scenario here, and reopen this issue.
