### ISSUE TITLE
Bug: KubeEleven panics after removing control nodes from k8s cluster

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#308]
### Current Behavior:

After removing control nodes from a k8s cluster `kube-eleven` panics.
### Expected Behavior:

A k8s cluster without control nodes doesn't makes sense, this shouldn't pass through the validation phase of the config or this case should be handled appropriately by not `panic`-ing
### Steps To Reproduce:

1. apply the following config
```yaml
kubernetes:
  clusters:
    - name: k8s-cluster
      version: v1.21.0
      network: 192.168.2.0/24
      pools:
        control:
          - hetzner-control
        compute:
          - hetzner-compute
```
2. Apply new config with removed control nodes
```yaml
kubernetes:
  clusters:
    - name: k8s-cluster
      version: v1.21.0
      network: 192.168.2.0/24
      pools:
        control:
        compute:
          - hetzner-compute
```
3. Wait till the workflow reaches `kube-eleven` and see the panic message
```bash
panic: runtime error: index out of range [0] with length 0

goroutine 13 [running]:
github.com/Berops/claudie/services/kube-eleven/server/kube-eleven.(*KubeEleven).getClusterNodes(0x2c?)
        /Users/despire/go/src/github.com/berops/claudie/services/kube-eleven/server/kube-eleven/kube-eleven.go:160 +0x2b6
github.com/Berops/claudie/services/kube-eleven/server/kube-eleven.(*KubeEleven).generateTemplateData(0xc000333f38)
        /Users/despire/go/src/github.com/berops/claudie/services/kube-eleven/server/kube-eleven/kube-eleven.go:112 +0xff
github.com/Berops/claudie/services/kube-eleven/server/kube-eleven.(*KubeEleven).generateFiles(0xc000333f38)
        /Users/despire/go/src/github.com/berops/claudie/services/kube-eleven/server/kube-eleven/kube-eleven.go:87 +0xf3
github.com/Berops/claudie/services/kube-eleven/server/kube-eleven.(*KubeEleven).BuildCluster(0xc000333f38)
        /Users/despire/go/src/github.com/berops/claudie/services/kube-eleven/server/kube-eleven/kube-eleven.go:46 +0x165
main.(*server).BuildCluster.func1.1()
        /Users/despire/go/src/github.com/berops/claudie/services/kube-eleven/server/server.go:42 +0x66
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/despire/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/despire/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa5
exit status 2
make: *** [kubeEleven] Error 1
```
