### ISSUE TITLE
Bug: Workflow fails if Lb, K8s clusters have the same name

### ISSUE THREAD

**Issue by Despire** [Berops/claudie#347]
### Current Behavior:

If the name of the load-balancer cluster is the same as the name of the targeted k8s cluster the workflow for building the cluster will fail on the ansibler serivce.
### Expected Behavior:

Choosing the same name for the lb & k8s cluster a very likely scenario, thus the workflow shouldn't fail.

### Steps To Reproduce:
1. Create a config with the following contents (same name for Lbs and K8s cluster)

```yaml
kubernetes:
  clusters:
    - name: matus-t1
      version: v1.21.0
      network: 192.168.2.0/24
      pools:
        control:
          - hetzner-control
        compute:
          - hetzner-compute

loadBalancers:
  roles:
    - name: apiserver-lb
      protocol: tcp
      port: 6443
      target_port: 6443
      target: k8sControlPlane
  clusters:
    - name: matus-t1
      roles:
        - apiserver-lb
      dns:
        dns_zone: lb-zone-2
        provider: gcp-1
      targeted-k8s: matus-t1
      pools:
        - hetzner-lb
```
2. Wait till the workflow reaches ansibler and see that only the Lb nodes will be reached the other nodes will fail.

```bash
VPN - services/ansibler/server/clusters/matus-t1-niqh   TASK [Wait 300 seconds for target connection to become reachable/usable] *******
VPN - services/ansibler/server/clusters/matus-t1-niqh   ok: [matus-t1-umxtdzo-hetzner-lb-1]
VPN - services/ansibler/server/clusters/matus-t1-niqh   ok: [matus-t1-umxtdzo-hetzner-lb-2]
VPN - services/ansibler/server/clusters/matus-t1-niqh   fatal: [matus-t1-6ozhsoi-hetzner-compute-2]: FAILED! => {"changed": false, "elapsed": 300, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: root@5.75.130.53: Permission denied (publickey,password)."}
VPN - services/ansibler/server/clusters/matus-t1-niqh   fatal: [matus-t1-6ozhsoi-hetzner-control-1]: FAILED! => {"changed": false, "elapsed": 300, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: root@5.75.130.74: Permission denied (publickey,password)."}
VPN - services/ansibler/server/clusters/matus-t1-niqh   fatal: [matus-t1-6ozhsoi-hetzner-compute-1]: FAILED! => {"changed": false, "elapsed": 300, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: root@5.75.130.67: Permission denied (publickey,password)."}
```
