### ISSUE TITLE
Feature: Migrate Claudie configuration to CRDs

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#357]
### Motivation:
Migrate Claudie manifests to CRD objects.

### Description:
The Claudie input manifest is currently a single input object carrying all the data. There might be a few benefits coming from a migration to CRD-based configs. This would reflect on the inputs (e.g. breaking into `Provider`, `Nodepool`, `LB`, `K8s`, `DNS`, `Credentials`, etc. CRDs) and perhaps on the outputs as well (not just a Kubeconfig output, but also status updates to the CRs, e.g. health and lifecycle statuses in `Nodepool`).

### Exit criteria:
- [ ] Propose a breakdown for input/output manifests into CRDs
- [ ] Compile pros/cons as a part of this task
- [ ] Implement the change accordingly

**Comment by bernardhalas** [comment]
We will not pursue this topic for now. We see the main (eventual) benefit from the CRD-driven state in the UX aspects. However, currently the state is scattered across several components: MongoDB, DynamoDB, object storage. It would not be straightforward to migrate the state to CRDs.

Hence, setting this aside for now.

**Comment by katapultcloud** [comment]
What we could do is to decouple only provider configuration to avoid secrets within the manifest:
```apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: aws
type: Opaque
data:
  access: xxx
  secret: xxx
---
apiVersion: claudie.io/v1alpha1
kind: ClaudieProvider
metadata:
  name: aws-1
spec:
  type: aws
  credentials:
    source: Secret
    secretRef:
      namespace: aws
      name: aws-creds
 ```
Then just specify the provider in the input manifest:
```nodePools:
  dynamic:
    - name: control-aws
      providerSpec:
        name: aws-1
        region: eu-central-1
        zone: eu-central-1c
      count: 2
      serverType: t3.medium
      image: ami-0965bd5ba4d59211c
```
Or point provider configuration in input yaml to a kube secret:
```
providers:
  aws:
    - name: aws-1
      accessKey: 
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: access
      secretKey: 
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: secret
```
