### ISSUE TITLE
Feature: Add support for CloudFlare DNS provider

### ISSUE THREAD

**Issue by cloudziu** [Berops/claudie#409]
### Motivation:
As disscused on Slack - CloudFlare is of the major DNS providers. I have experience with companies that had resources in multiple cloud providers and used CloudFlare as their main DNS provider - when needed, they delegated a subdomain to S3/Azure DNS etc

### Description:
Add support for CloudFlare DNS provider for Claudie. It will probably require adding CloudFlare in providers section.
Example:
```yaml
providers:
  hetzner: [ ]
  oci: [ ]
  cloudflare:
    - name: cf-1
      email: { $email }
      apiToken: { $apiToken }
```

### Exit criteria:
- [ ] Ability to use CloudFlare in Claudie as DNS provider
