### ISSUE TITLE
Feature: OCI Nodes: Give ability to use Flex Instances

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#410]
### Motivation:
1. Leveraging the ability of customising OCI Flex instances would be a nice UX feature.
2. Instances with fixed sizes so called "Previous Generation Shapes" according to the [docs](https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm#previous-generation-shapes) are all after _End of orderability date_. At this moment we are able to provision them with Terraform, but this can change/limited at any time.  

### Description:
User can set custom values for nodes from OCI. 
Example:
```yaml
# claudie-manifest.yml
nodePools:
  dynamic:
 - name: oci-control
      providerSpec:
        name: oci-1
        region: eu-frankfurt-1
        zone: hsVQ:EU-FRANKFURT-1-AD-3
        ocpus: 4
        memory_in_gbs: 100
      count: 1
      server_type: VM.Standard.E4.Flex
```

### Exit criteria:
- [ ] User have ability to customise OCI nodes resources in a more granular way

**Comment by MiroslavRepka** [comment]
Hey guys, here is my proposal to future-proof similar features other cloud providers may offer.

```yaml
# claudie-manifest.yml
nodePools:
  dynamic:
    - name: my-nodepool
      providerSpec:
        name: provider-name
        region: region-1
        zone: zone-1
      count: 1
      server_type: VM1
      ...
      terraformArgs: # not sure about the name, can be "parameters", "add-ons",  etc.
        <field-1>: value-1
        <field-2>: value-2
        ...
        <field-n>: value-n
```
which in protobuf would be reflected as 
```proto
message NodePool {
  string name = 1;
  string region = 2;
  string serverType = 3;
  string image = 4;
  uint32 diskSize = 5;
  string zone = 6;
  uint32 count = 9;
  repeated Node nodes = 10;
  Provider provider = 11 ;
  bool isControl = 12;
  map<string, string> terraformArgs = 13;
}
```
which in templates will be as
```tpl
resource "<node-instance>" "{{ $nodepool.Name }}" {
  provider = aws.k8s-nodepool
  count = {{ $nodepool.Count }}

  # add user-defined fields
  {{ range $field, $value := $nodepool.TerraformArgs }}
   {{ $field }} =  {{ $value }}
  {{ end }}
}
```
What do you think @bernardhalas @MarioUhrik @jaskeerat789 @Despire?

The only concern I have is the validation - if all attributes are correct/valid. But I guess, we can leave it up to the user.

**Comment by bernardhalas** [comment]
Hi @MiroslavRepka , just a minor feedback. This approach would leave us only with key/value pairs in the `nodepools.dynamic.*.terraformArgs` stanza. Do we want to limit it this way? Can we make this even more generic? :)
If we consider making it generic, this would mean finding a way to serialize it, which might not be trivial, right?

Also, I'd leave out the `terraform` part of the stanza. I don't see the value in exposing this to the user, do you?

**Comment by MarioUhrik** [comment]
I understand your proposal.
I'm not sure about it.

I agree with Bernard that it exposes way too much of the "under-the-hood" implementation.
I also think it gives too much potential power to the user.

I would expect Claudie to have its own truly proper, cloud agnostic interface, instead of being just a thin wrapper for Terraform.
From that PoV, I rather lean towards Adam's proposal.

How about this ?

```
# claudie-manifest.yml
nodePools:
  dynamic:
 - name: oci-control
      providerSpec:
        name: oci-1
        region: eu-frankfurt-1
        zone: hsVQ:EU-FRANKFURT-1-AD-3
      count: 1
      machine:
          shape: VM.Standard.E4.Flex # mandatory
          ocpus: 4 # optional
          memory_in_gbs: 100 # optional
```

I would be OK with leaving this ungroomed and deferring the decision to a later point.
