### ISSUE TITLE
Bug: Workflow fails to build

### ISSUE THREAD

**Issue by Despire** [berops/claudie#606]
EDIT:

This issue is about figuring out which changes should be applied first. Given a change in the desired state where we change the kubernetes version add/remove LBs or nodes or change worker/control planes we should figure out which steps (running kube-eleven, or Terraformer, ansibler etc...) should be executed first.

An example is given below where the current workflow fails

### Current Behaviour

When you change the `control nodes` and attach a `Loadbalancer` in a config, the workflow fails on setting up the loadbalancers when trying to execute the `change api endpoints` ansible playbook as the new control node just completed the terraformer stage so these components are not installed yet (until the KUBE-ELEVEN stage which won't be reached).

### Expected Behaviour

I would expect to skip setting up the loadbalancers in the first stage of the processing and then set them up in the second stage.

### Steps To Reproduce

1. apply a very basic config
```yaml
kubernetes:
  clusters:
    - name: matus-ts3
      version: v1.22.0
      network: 192.168.2.0/24
      pools:
        control:
          - hetzner-control
        compute:
          - hetzner-compute
```

2. change the control node and attach a LB

```yaml
kubernetes:
  clusters:
    - name: test
      version: v1.22.0
      network: 192.168.2.0/24
      pools:
        control:
          - gcp-control
        compute:
          - hetzner-compute
loadBalancers:
  roles:
    - name: apiserver-lb
      protocol: tcp
      port: 6443
      targetPort: 6443
      target: k8sControlPlane
  clusters:
    - name: test-lb
      roles:
        - apiserver-lb
      dns:
        dnsZone: claudie.dev
        provider: cloudflare-1
      targetedK8s: test
      pools:
        - gcp-lb
```

3. the wofklow fails in ANSIBLE stage when setting up the load balancers
