### ISSUE TITLE
Bug: Gather facts manually before runnig playbook

### ISSUE THREAD

**Issue by MiroslavRepka** [berops/claudie#646]
### Current Behaviour

After PR #545, the unattended-upgrades are disabled as a part of the wiregurad playbook. However, as they enabled gathering facts by `gather_facts: true`, they often need a retry as VMs, that is freshly created are not yet accessible by ssh. This slows down the whole execution, as we often have to wait for ~50s just due to retry.

### Expected Behaviour

We should wait until all VMs are accessible, before gathering facts.

### Steps To Reproduce
1. Create a simple input manifest
2. Apply it to the Claudie
3. Monitor Ansibler

### Anything else to note

One possible approach to fix this would be to gather facts manually by running `ansible.builtin.setup` module, AFTER the step where we [wait for the connection to become usable](https://github.com/berops/claudie/blob/master/services/ansibler/server/ansible-playbooks/wireguard.yml#L8). I.e
```yaml
---
- hosts: nodes
  remote_user: root
  gather_facts: false # Change to false
  become: yes

  pre_tasks:
    - name: Wait 300 seconds for target connection to become reachable/usable
      wait_for_connection:
        timeout: 300
    # Gather facts manually
    - name: Gather facts
      ansible.builtin.setup:
```
