### ISSUE TITLE
Feature: Resource requests/limits for Claudie K8s Deployments and Autoscaler tuning

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#67]
### Motivation:

At the moment, we're having issues due to pods not being schedulable, and GKE being totally helpless:

```
 Warning  FailedScheduling   2m17s (x28 over 41m)   gke.io/optimize-utilization-scheduler  0/8 nodes are available: 7 Insufficient memory, 8 Insufficient cpu.
  Normal   NotTriggerScaleUp  2m14s (x227 over 38m)  cluster-autoscaler                     pod didn't trigger scale-up (it wouldn't fit if a new node is added): 5 in backoff after failed scale-up
```

Furthermore, the pods actually get assigned some default resource requests/limits, but they are probably ridiculously high for the dev environment.

```
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
```

### Description:

We should define resource requests for each K8s deployment, with sensible values.
That will help us avoid future problems with the pods being unschedulable, and it will enable us to fit more pods into less nodes.

### Exit criteria:
- [x] All K8s deployments have a `resources:` section specified with sensible values based on real resource usage. Relevant MR is reviewed and merged.
- [x] Check the cluster autoscaler behavior and tuning
