### ISSUE TITLE
Feature: offload provider secrets from input manifest

### ISSUE THREAD

**Issue by katapultcloud** [berops/claudie#787]
### Motivation 

Currently input manifest has to contain all cloud secrets in plain text. 

### Description

Having secrets outside of input manifest and have a reference in provider configuration.

Example:
```
kind: Secret
metadata:
  name: aws-creds
  namespace: aws
type: Opaque
data:
  access: xxx
  secret: xxx
---
providers:
  aws:
    - name: aws-1
      accessKey: 
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: access
      secretKey: 
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: secret
```

### Exit criteria

- [ ] Secrets declared outside of input manifest

Part of #357
