### ISSUE TITLE
Feature: Error handling with gRPC

### ISSUE THREAD

**Issue by Despire** [berops/claudie#795]
### Motivation

gRPC has very basic error handling by [default](https://grpc.io/docs/guides/error/#standard-error-model) which is limiting as to what can be send as a response and what can't

### Description

Consider the following scenario, you create a secret to build the following cluster:

```yaml
kubernetes:
  clusters:
    - name: t1
      version: v1.24.0
      network: 192.168.2.0/24
      pools:
        control:
          - gcp-control
        compute:
          - gcp-compute
loadBalancers:
  roles:
    - name: apiserver-lb
      protocol: tcp
      port: 6443
      targetPort: 6443
      target: k8sControlPlane
  clusters:
    - name: t1-lb
      roles:
        - apiserver-lb
      dns:
        dnsZone: claudie.dev
        provider: cloudflare-1
      targetedK8s: t1
      pools:
        - gcp-lb
```

The k8s cluster is build successfully in the `terraformer` service but the LB cluster failed, terraformer returns an error and the context of what infra was build is lost, on the calling side in the `builder` service the workflow ends with an error which is stored in the DB alongside with the current state (which won't reflect the actual current state) and the desired state.

The issue is, now we want to delete the secret and thus delete the infra, which will fail. Why ? because we've lost information about what was build and what was not, and when we enter the deletion stage of the config we work with the current state which doesn't reflect the actual current stage.

the generated `.pb.go` files ignore any response if an error is returned by the RPC.

https://github.com/berops/claudie/blob/555143786993ca227771dad0247e7439909b1ae4/proto/pb/terraformer_grpc.pb.go#L39-L46

**If an error occurs while a service is processing the changes and some get applied and some won't, if we send a response along with the error, so that the calling side would have the changes in the current state reflecting the infra, it gets ignored on the calling side.**

The aim is to resolve this issue coming up with an solution, such that we have both the changes made and the error on the calling side of the gRPC call.

Possible ideas:
 - Ignore `error` in the gRPC calls (i.e. always return a `nil` error), instead include it in the response and the calling side would have to check the error in the response body.
- gRPC [rich error model](https://grpc.io/docs/guides/error/#richer-error-model)

### Exit criteria

- [ ]  The calling side should receive both the error and the current state of the cluster (including any partial changes made until the point of failure where the error occurred)
