### ISSUE TITLE
Feature: support adding taints to node pools

### ISSUE THREAD

**Issue by katapultcloud** [berops/claudie#829]
### Motivation

Taints and labels should be able to be added to node pools to prevent workloads scheduled onto nodes where they don't belong.

### Description

Taint and label sections in input-manifest to define user defined taints and labels:

example
```
nodePools:
  dynamic:
    - name: hetzner-control
      providerSpec:
        name: hetzner-1
        region: nbg1
        zone: nbg1-dc3
      count: 1
      serverType: cpx11
      image: ubuntu-22.04
      storageDiskSize: 50
      taints:
        key1=value1:NoSchedule
        key2=value2:NoExecute
      labels:
        key1=value1
        key2=value2
```

### Exit criteria

- [ ] node pools can be created with custom taints
- [ ] node pools can be created with custom labels
