### ISSUE TITLE
Feature: Run CD pipeline after the merge to master branch

### ISSUE THREAD

**Issue by samuelstolicny** [berops/claudie#84]
### Motivation:

Right now, the CD pipeline is called right after every successful CI. This approach is not considered the best because the codebase from PR will propagate to the dev deployment aka "claudie namespace" in our dev cluster after PR is created not after it's considered as working and merged to the master branch.

### Description:

Run CD pipeline after the merge to master, not after successful CI.

Path to the CD pipeline YAML: `.github/workflows/CD-pipeline-dev.yml`
Current trigger:
```
on:
  # Run after CI
  workflow_run:
    workflows: [ "CI pipeline for platform" ] 
    types: [ completed ]
  # Manual trigger    
  workflow_dispatch:
```

### Exit criteria:
- [x] Change CD pipeline trigger 

This one should be really quick so I consider it as a "good first issue", but let's groom it first.
