### ISSUE TITLE
Bug: an ERROR state cluster block DONE state clusters

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#861]
Consider an input manifest

```yaml
  providers:
    - name: hetzner-secret
      providerType: hetzner
      secretRef:
        name: hetzner
        namespace: claudie    
  nodePools:
    dynamic:
      - name: control-hetzner-1
        providerSpec:
          name: hetzner-secret
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-22.04

      - name: compute-hetzner-1
        providerSpec:
          name: hetzner-secret
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-22.04
        storageDiskSize: 50    

      - name: control-hetzner-2
        providerSpec:
          name: hetzner-secret
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-22.04

      - name: compute-hetzner-2
        providerSpec:
          name: hetzner-secret
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-22.04
        storageDiskSize: 50          
  kubernetes:
    clusters:
      - name: first-cluster
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - control-hetzner-1
          compute:
            - compute-hetzner-1

      - name: second-cluster
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - control-hetzner-2
          compute:
            - compute-hetzner-2
```

and the cluster Statuses are:
```json
  "clusters": {
    "first-cluster": {
      "message": "error in Kube-eleven for cluster hetzner-test-cluster project default/hetzner-test-manifest : rpc error: c
ode = Unknown desc = error while building cluster hetzner-test-cluster for project default/hetzner-test-manifest : error whi
le running \"kubeone apply\" in services/kube-eleven/server/clusters/hetzner-test-cluster-n2fmpui : exit status 15",
      "phase": "KUBE_ELEVEN",
      "state": "ERROR"
    },
    "second-cluster": {
      "phase": "NONE",
      "state": "DONE"
    }
  },
```
Because of the ERROR in the `first-cluster`, the user won't be able to operate on the `second-cluster`. The only action he can take is to remove the input-manifest.
