### ISSUE TITLE
Bug: NodePool reused as Master and Workers

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#865]
Example InputManifest:
```yaml
  nodePools:
    dynamic:
      - name: hetzner-1
        providerSpec:
          name: hetzner-secret
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-22.04
           
  kubernetes:
    clusters:
      - name: hetzner-test-cluster
        version: v1.24.0
        network: 192.168.2.0/24
        pools:
          control:
            - hetzner-1
          compute:
            - hetzner-1
```
In this scenario when using a single nodePool to be used as a `control` and `compute` in a kubernetes cluster, there are errors in Terraformer while initializing the backend.
```
hetzner-test-cluster-6j5l93e	 Initializing the backend...
hetzner-test-cluster-6j5l93e	 There are some problems with the configuration, described below.
hetzner-test-cluster-6j5l93e
hetzner-test-cluster-6j5l93e	 The Terraform configuration must be valid before initialization so that
hetzner-test-cluster-6j5l93e	 Terraform can determine which modules and providers need to be installed.
hetzner-test-cluster-6j5l93e	 ╷
hetzner-test-cluster-6j5l93e	 │ Error: Duplicate resource "hcloud_server" configuration
hetzner-test-cluster-6j5l93e	 │
hetzner-test-cluster-6j5l93e	 │   on hetzner-test-cluster-6j5l93e-hetzner-secret.tf line 82:
hetzner-test-cluster-6j5l93e	 │   82: resource "hcloud_server" "hetzner-test-cluster-6j5l93e-hetzner-1-1" {
hetzner-test-cluster-6j5l93e	 │
hetzner-test-cluster-6j5l93e	 │ A hcloud_server resource named "hetzner-test-cluster-6j5l93e-hetzner-1-1"
hetzner-test-cluster-6j5l93e	 │ was already declared at
hetzner-test-cluster-6j5l93e	 │ hetzner-test-cluster-6j5l93e-hetzner-secret.tf:59,1-68. Resource names must
hetzner-test-cluster-6j5l93e	 │ be unique per type in each module.
hetzner-test-cluster-6j5l93e	 ╵
hetzner-test-cluster-6j5l93e
hetzner-test-cluster-6j5l93e	 ╷
hetzner-test-cluster-6j5l93e	 │ Error: Duplicate output definition
hetzner-test-cluster-6j5l93e	 │
hetzner-test-cluster-6j5l93e	 │   on hetzner-test-cluster-6j5l93e-hetzner-secret.tf line 129:
hetzner-test-cluster-6j5l93e	 │  129: output "hetzner-1" {
hetzner-test-cluster-6j5l93e	 │
hetzner-test-cluster-6j5l93e	 │ An output named "hetzner-1" was already defined at
hetzner-test-cluster-6j5l93e	 │ hetzner-test-cluster-6j5l93e-hetzner-secret.tf:77,1-19. Output names must
hetzner-test-cluster-6j5l93e	 │ be unique within a module.
hetzner-test-cluster-6j5l93e	 ╵
hetzner-test-cluster-6j5l93e
```

This should be fixed or be referenced in the documentation.
